from __future__ import annotations

import hashlib
import sqlite3
from pathlib import Path

from opencepgeo.database import SCHEMA_VERSION, _SCHEMA


def write_service_database(
    path: Path,
    *,
    schema_version: str = SCHEMA_VERSION,
    dataset_version: str = "fixture-service-v1",
) -> str:
    connection = sqlite3.connect(path)
    connection.executescript(_SCHEMA)
    connection.executemany(
        "INSERT INTO metadata (key, value) VALUES (?, ?)",
        (
            ("format", schema_version),
            ("dataset_version", dataset_version),
            ("count_unique_ceps", "6"),
            ("count_located", "5"),
            ("count_unresolved", "1"),
        ),
    )
    connection.executemany(
        """
        INSERT INTO cep_geo (
            cep, prefix, street, complement, unit, neighborhood,
            city, uf, state, region, ibge, latitude, longitude,
            precision, method, evidence_count, evidence_radius_km,
            geo_source, evidence_digest, dataset_version
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            (
                "01001000",
                "01001",
                "Praça da Sé",
                None,
                None,
                "Sé",
                "São Paulo",
                "SP",
                "São Paulo",
                "Sudeste",
                "3550308",
                -23.5505,
                -46.6333,
                "observed_cep",
                "robust_median_first_party",
                1,
                0.0,
                '["fixture"]',
                "sha256:" + "0" * 64,
                dataset_version,
            ),
            (
                "01001001",
                "01001",
                "Rua Um",
                None,
                None,
                "Sé",
                "São Paulo",
                "SP",
                "São Paulo",
                "Sudeste",
                "3550308",
                -23.551,
                -46.634,
                "observed_cep",
                "robust_median_first_party",
                1,
                0.0,
                '["fixture"]',
                "sha256:" + "1" * 64,
                dataset_version,
            ),
            (
                "01001002",
                "01001",
                "Rua Dois",
                None,
                None,
                "Sé",
                "São Paulo",
                "SP",
                "São Paulo",
                "Sudeste",
                "3550308",
                -23.5495,
                -46.632,
                "osm_postcode",
                "robust_median_osm_postcode",
                1,
                0.0,
                '["openstreetmap"]',
                "sha256:" + "2" * 64,
                dataset_version,
            ),
            (
                "01001003",
                "01001",
                "Rua Três",
                None,
                None,
                "Sé",
                "São Paulo",
                "SP",
                "São Paulo",
                "Sudeste",
                "3550308",
                -23.7,
                -46.8,
                "municipality",
                "ibge_city_reference_with_locality_dispersion",
                1,
                20.0,
                '["ibge"]',
                "sha256:" + "3" * 64,
                dataset_version,
            ),
            (
                "01001004",
                "01001",
                "Rua Quatro",
                None,
                None,
                "Centro",
                "Rio de Janeiro",
                "RJ",
                "Rio de Janeiro",
                "Sudeste",
                "3304557",
                -22.9068,
                -43.1729,
                "observed_cep",
                "robust_median_first_party",
                1,
                0.0,
                '["fixture"]',
                "sha256:" + "4" * 64,
                dataset_version,
            ),
            (
                "99999999",
                "99999",
                None,
                None,
                None,
                None,
                "Cidade sem ponto",
                "ZZ",
                None,
                None,
                "9999999",
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                dataset_version,
            ),
        ),
    )
    connection.commit()
    connection.execute("VACUUM")
    connection.close()
    return hashlib.sha256(path.read_bytes()).hexdigest()
